# For Convox

version: '2'
services:

  #=================================
  # Services
  #=================================

  merry-poppins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080/tcp
      - 443:8080/tcp
    environment:
      - PORT=8080
    labels:
      - convox.port.443.protocol=https
